# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37-tf1150:
        python.version: '3.7'
        KERAS: keras==2.4.3
        TENSORFLOW_PATH: tensorflow==1.15.0
        INSTALL_ORT: pip install onnxruntime==1.6.0

      # ORT hasn't support Python 3.8 yet.
      Python38-tf220:
        python.version: '3.8'
        KERAS: keras==2.4.3
        TENSORFLOW_PATH: tensorflow==2.2.0
        INSTALL_ORT:

    maxParallel: 3

  steps:
  - script: sudo install -d -m 0777 /home/vsts/.conda/envs
    displayName: Fix Conda permissions

  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: true
      environmentName: 'py$(python.version)'
      packageSpecs: 'python=$(python.version)'

  - script: |
      python -m pip install --upgrade pip
      conda config --set always_yes yes --set changeps1 no
      pip install -i https://test.pypi.org/simple/ onnx==1.8.102
      pip install h5py==2.9.0
      pip install $(TENSORFLOW_PATH)
      pip install $(KERAS)
      pip install git+https://github.com/microsoft/onnxconverter-common
      pip install -r requirements.txt
      pip install -r requirements-dev.txt
      $(INSTALL_ORT)
    displayName: 'Install dependencies'

  - script: |
      pip install -e .
      python -c "import onnxruntime"
      python -c "import onnxconverter_common"
      export TF_KERAS=0
      pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - script: |
      flake8 keras2onnx
    displayName: 'flake8'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
